model:
  target: model.michelangelo.models.tsal.sal_vqvae_pl_module.AlignedShapeAsLatentVQPLModule
  params:
    shape_module_cfg:
      target: model.michelangelo.models.tsal.sal_vqvae.AlignedShapeLatentVQPerceiver
      params:
        num_latents: 256
        embed_dim: 32
        point_feats: 11
        num_freqs: 8
        include_pi: false
        heads: 12
        width: 512
        num_encoder_layers: 6
        num_decoder_layers: 12
        use_ln_post: true
        init_scale: 0.25
        qkv_bias: false
        use_checkpoint: true
        codebook_size: 8192
        codebook_dim: 1024
        commitment_cost: 0.25
        vq_decay: 0.99
        gs_decoder_output_dim: 40000 * 14
    aligned_module_cfg:
      target: model.michelangelo.models.tsal.clip_asl_module.CLIPAlignedShapeAsLatentModule

    loss_cfg:
      target: model.michelangelo.models.tsal.sal_vqvae_pl_module.VQLoss
      params:
        commitment_weight: 1.0
        codebook_weight: 1.0

    optimizer_cfg:
      optimizer:
        target: torch.optim.AdamW
        params:
          betas: [ 0.9, 0.99 ]
          eps: 1e-6
          weight_decay: 1e-2

      scheduler:
        target: model.michelangelo.utils.trainings.lr_scheduler.LambdaWarmUpCosineFactorScheduler
        params:
          warm_up_steps: 5000
          f_start: 1e-6
          f_min: 1e-3
          f_max: 1.0
